### ISSUE TITLE
Error deploying scriptable-transform processor

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#165]
As a user, while deploying a stream in SCDF with `scriptable-transform` processor, I'm seeing the following exception and the app fails to bootstrap. This app fails with the same error when launched as `java -jar .....` as well.

**stream:**
```
dataflow:>stream create test --definition "time | scriptable-transform --script='return payload' --language=groovy | log" --deploy
```

**error:**
```
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.stream.app.scriptable.transform.processor.ScriptableTransformProcessorConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.integration.scripting.ScriptVariableGenerator org.springframework.cloud.stream.app.scriptable.transform.processor.ScriptableTransformProcessorConfiguration.scriptVariableGenerator; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.integration.scripting.ScriptVariableGenerator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2016-06-23 11:34:07.599  INFO 40824 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2016-06-23 11:34:07.620 ERROR 40824 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.stream.app.scriptable.transform.processor.ScriptableTransformProcessorConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.integration.scripting.ScriptVariableGenerator org.springframework.cloud.stream.app.scriptable.transform.processor.ScriptableTransformProcessorConfiguration.scriptVariableGenerator; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.integration.scripting.ScriptVariableGenerator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
```

**Comment by artembilan** [comment]
Well, looks like all those new `ScriptVariableGeneratorConfiguration` aren't `@Import`'ed to the main `@EnableBinding` class.
Not sure what was forced you to move away from the common module, but that copy/paste led us to this nasty bug.
We can have a super class (`abstract ScriptProperties` ?) and the same `ScriptVariableGeneratorConfiguration` but on one place. Import such a module to all of these script-aware modules for extension and, of course, don't forget to add `@Import(ScriptVariableGeneratorConfiguration.class)`.

**Comment by artembilan** [comment]
All tests pass in the project because they are placed in the same package as main classes, e.g.
`org.springframework.cloud.stream.app.scriptable.transform.processor`
for `ScriptableTransformProcessorConfiguration` and its not imported `ScriptVariableGeneratorConfiguration`. And the same package for `ScriptableTransformProcessorIntegrationTests`.
But look, we use there this one:
```
@SpringBootApplication
public static class ScriptableTransformProcessorApplication {

}
```
which has `@ComponentScan` with default scan strategy for current package.

Or we should place tests in the separate package, for example `org.springframework.cloud.stream.app.scriptable.transform.processor.test`,
with `@Import` for main app class;
or avoid to use `@SpringBootApplication` altogether!

**Comment by ericbottard** [comment]
Issued https://github.com/spring-cloud/spring-cloud-stream-app-starters/pull/169 for now
But I'm not sure I understand your interpretation of why the tests pass @artembilan 
Even though we're in the same package, where does the `ScriptVariableGeneratorConfiguration` come from in that case?
