### ISSUE TITLE
spring-cloud-stream-app-starters/gpfdist kubernetes problem 

### ISSUE THREAD

**Issue by rut78HR** [spring-cloud/spring-cloud-stream-app-starters#276]
Hello ..  I setup simple mastre-slave cluster on kubernetes v.1.4 with kubeadm .. I follow tutorial from this location : http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.1.0.RC1/reference/htmlsingle/  
I don't have google cloud for persistent disk so i skip these step. With some modification i managed to run scdf and make simple test time|log wich pass successful. Now im trying to setup simple http|gpfdist stream but without luck. First of all i noticed that i don't have parameters properties in scdf dashboard for selected source/sink :
https://s17.postimg.org/4a6uku68v/Screenshot_from_2016_11_30_20_06_23.png

I provide these parameters and create stream .  deploy .. http pod starts and run. To be sure i try telenet to port 10001 and it works. But problem is with gpfdist sink which ignore all parameters i provide 
https://s18.postimg.org/sysv46sgp/Screenshot_from_2016_11_30_20_05_31.png

Here is log from deployed gpfdist log (full log is on pastebin  http://pastebin.com/Wa1MkE8g  ) 

scdf apps are from : http://bit.ly/Avogadro-RC1-stream-applications-kafka-docker

> 2016-11-30 18:39:03.134  INFO 1 --- [           main] kafka.producer.SyncProducer              : Connected to 10.36.0.14:9092 for producing
2016-11-30 18:39:03.238  INFO 1 --- [           main] kafka.producer.SyncProducer              : Disconnecting from 10.36.0.14:9092
2016-11-30 18:39:03.344  INFO 1 --- [5-kafka-zk:2181] org.I0Itec.zkclient.ZkEventThread        : Terminate ZkClient event thread.
2016-11-30 18:39:03.366  INFO 1 --- [           main] org.apache.zookeeper.ZooKeeper           : Session: 0x158b55283440044 closed
2016-11-30 18:39:03.366  INFO 1 --- [ain-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down
2016-11-30 18:39:03.439  INFO 1 --- [           main] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=kafka-zk:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@15224191
2016-11-30 18:39:03.439  INFO 1 --- [3-kafka-zk:2181] org.I0Itec.zkclient.ZkEventThread        : Starting ZkClient event thread.
2016-11-30 18:39:03.440  INFO 1 --- [ter.local:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server kafka-zk.default.svc.cluster.local/10.104.85.35:2181. Will not attempt to authenticate using SASL (unknown error)
2016-11-30 18:39:03.441  INFO 1 --- [ter.local:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to kafka-zk.default.svc.cluster.local/10.104.85.35:2181, initiating session
2016-11-30 18:39:03.460  INFO 1 --- [ter.local:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server kafka-zk.default.svc.cluster.local/10.104.85.35:2181, sessionid = 0x158b55283440046, negotiated timeout = 6000
2016-11-30 18:39:03.460  INFO 1 --- [ain-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (SyncConnected)
2016-11-30 18:39:04.446 ERROR 1 --- [TaskScheduler-1] o.s.c.s.a.g.sink.support.JdbcCommands    : Error during prepare sql
org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:390) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:439) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.cloud.stream.app.gpfdist.sink.support.JdbcCommands.prepare(JdbcCommands.java:119) [spring-cloud-starter-stream-sink-gpfdist-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
	at org.springframework.cloud.stream.app.gpfdist.sink.support.JdbcCommands.execute(JdbcCommands.java:87) [spring-cloud-starter-stream-sink-gpfdist-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
	at org.springframework.cloud.stream.app.gpfdist.sink.support.DefaultLoadService.load(DefaultLoadService.java:57) [spring-cloud-starter-stream-sink-gpfdist-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
	at org.springframework.cloud.stream.app.gpfdist.sink.support.DefaultGreenplumLoad.load(DefaultGreenplumLoad.java:45) [spring-cloud-starter-stream-sink-gpfdist-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
	at org.springframework.cloud.stream.app.gpfdist.sink.GpfdistMessageHandler$1.run(GpfdistMessageHandler.java:143) [spring-cloud-starter-stream-sink-gpfdist-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar!/:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar!/:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[commons-dbcp-1.4.jar!/:1.4]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	... 17 common frames omitted
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:252) ~[postgresql-9.4.1208.jre7.jar!/:9.4.1208.jre7]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.4.1208.jre7.jar!/:9.4.1208.jre7]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:215) ~[postgresql-9.4.1208.jre7.jar!/:9.4.1208.jre7]
	at org.postgresql.Driver.makeConnection(Driver.java:406) ~[postgresql-9.4.1208.jre7.jar!/:9.4.1208.jre7]
	at org.postgresql.Driver.connect(Driver.java:274) ~[postgresql-9.4.1208.jre7.jar!/:9.4.1208.jre7]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar!/:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar!/:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar!/:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar!/:1.4]
	... 21 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_102]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_102]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_102]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_102]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_102]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_102]
	at org.postgresql.core.PGStream.<init>(PGStream.java:64) ~[postgresql-9.4.1208.jre7.jar!/:9.4.1208.jre7]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:133) ~[postgresql-9.4.1208.jre7.jar!/:9.4.1208.jre7]
	... 29 common frames omitted
<

tnx

**Comment by rut78HR** [comment]
Ok . i managed to fix these problem with properties : 

> If you need to specify any of the app specific configuration properties then you must use "long-form" of them including the app specific prefix like --jdbc.tableName=TEST_DATA

but now i got another problem with mapping internal address to external 

ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
2016-12-01 18:52:46.603  INFO 1 --- [io-8080-exec-10] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 0.10.1.0
2016-12-01 18:52:46.603  INFO 1 --- [io-8080-exec-10] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : 3402a74efb23d1d4
2016-12-01 18:52:46.749  INFO 1 --- [io-8080-exec-10] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2016-12-01 18:52:46.758  WARN 1 --- [io-8080-exec-10] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused; nested exception is java.net.ConnectException: Connection refused
2016-12-01 18:53:22.642  INFO 1 --- [TaskScheduler-1] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2016-12-01 18:53:22.849  INFO 1 --- [TaskScheduler-1] o.s.jdbc.support.SQLErrorCodesFactory    : SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
2016-12-01 18:53:22.949 ERROR 1 --- [TaskScheduler-1] o.s.c.s.a.g.sink.support.JdbcCommands    : Error during run sql
org.springframework.dao.DataAccessResourceFailureException: StatementCallback; SQL [INSERT INTO httpdata SELECT * FROM httpdata_ext_90f5e4e4_d363_4ba2_aa01_2f55b73f7cf7]; ERROR: connection with gpfdist failed for gpfdist://10.36.0.27:8000/data. effective url: http://10.36.0.27:8000/data. error code = 110 (Connection timed out)  (seg0 slice1 dbslave01:40000 pid=28847); nested exception is org.postgresql.util.PSQLException: ERROR: connection with gpfdist failed for gpfdist://10.36.0.27:8000/data. effective url: http://10.36.0.27:8000/data. error code = 110 (Connection timed out)  (seg0 slice1 dbslave01:40000 pid=28847)
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:105) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

How to fix these ?

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/gpfdist#6
