### ISSUE TITLE
Concurrent access issue in websocket sink module

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#60]
_From @ericbottard on November 18, 2015 20:14_

As witnessed in https://travis-ci.org/spring-cloud/spring-cloud-stream-modules/builds/91894403

That whole static thing being accessed from same package classes seems phony anyway

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#113_

**Comment by sabbyanandan** [comment]
_From @markpollack on December 10, 2015 16:3_

closed by accident in PR comment.

**Comment by sabbyanandan** [comment]
_From @markpollack on December 11, 2015 22:14_

This is still a persistent error in travis (but not bamboo CI builds)

```
Running org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 27.248 sec <<< FAILURE! - in org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests
testSingleMessageMultipleSubscribers(org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests)  Time elapsed: 10.059 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests$WebsocketSinkClientHandler.await(WebsocketSinkIntegrationTests.java:198)
	at org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests.testSingleMessageMultipleSubscribers(WebsocketSinkIntegrationTests.java:110)
```

from https://travis-ci.org/spring-cloud/spring-cloud-stream-modules/builds/96364432

**Comment by sabbyanandan** [comment]
_From @ericbottard on December 12, 2015 10:9_

I've seen it locally as well. Good thing "websocket" starts with a w, and this is the last module... But there is definitely something going on there

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/websocket#1
