### ISSUE TITLE
Cassandra sink's --initScript option is not working 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#66]
_From @sabbyanandan on December 16, 2015 0:1_

As a user, I'm creating a stream [on `local` SPI] with `--initScript` option to create the table for the `cassandra` sink; however, I'm unable to get the table created successfully.

**stream:**

```
stream create cassandraTest --definition "http | cassandra --initScript=file:<absolut-path-to>/int-db.cql --ingestQuery='insert into book (isbn, title, author) values (uuid(), ?, ?)'" --deploy
```

**data:**

```
dataflow:>http post --contentType 'application/json' --data "{\"title\": \"Test\", \"author\": \"Sabby\"}" --target http://localhost:16784/messages
POST (application/json;charset=UTF-8) http://localhost:16784/messages {"title": "Test", "author": "Sabby"}
202 ACCEPTED
```

**error:**

```
org.springframework.messaging.MessageHandlingException: error occurred in message handler [cassandraSinkMessageHandler]; nested exception is com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured columnfamily book
    at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139) ~[spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147) ~[spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120) ~[spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77) ~[spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442) [spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:392) [spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) [spring-messaging-4.2.4.BUILD-SNAPSHOT.jar!/:4.2.4.BUILD-SNAPSHOT]
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) [spring-messaging-4.2.4.BUILD-SNAPSHOT.jar!/:4.2.4.BUILD-SNAPSHOT]
    at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) [spring-messaging-4.2.4.BUILD-SNAPSHOT.jar!/:4.2.4.BUILD-SNAPSHOT]
    at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231) ~[spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154) ~[spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102) ~[spring-integration-core-4.2.3.RELEASE.jar!/:na]
    at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105) ~[spring-integration-core-4.2.3.RELEASE.jar!/:na]
```

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#129_

**Comment by sabbyanandan** [comment]
_From @artembilan on December 16, 2015 0:37_

@sabbyanandan , are you sure that `initScript` file has name like `int-db.cql`?
We have fixed it in module tests to the `init-db.cql`.
Plus, share, please, the logs from the `cassandra` application after the stream deploy.

**Comment by sabbyanandan** [comment]
_From @artembilan on December 16, 2015 19:0_

BTW, the option must be like `spring.cassandra.init-script`. 
The import part is the `spring.cassandra.` prefix. 
Just because we have separate, common properties like `CassandraProperties` and specific to the `sink` - `CassandraSinkProperties`. Assuming that we may have `Cassandra Source` in the future.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/cassandra#2
